### ISSUE TITLE
visitWithAudit helper

### ISSUE THREAD

**Issue by ondrejsevcik** [ember-a11y/ember-a11y-testing#102]
Hi, it would be nice to have a helper where the `visit` and `a11yAudit` are combined into one so I don't forget to run audit. 

```
// before
await visit('/');
await a11yAudit();

// after
await visitWithAudit('/');
```

Maybe there is a better name than `visitWithAudit`, but you got the idea ;)

**Comment by rwjblue** [comment]
Going to close this one (sorry @ondrejsevcik), I think we should refocus and target some specific features to do this via the new (private for now) hooks added in emberjs/ember-test-helpers#878.
