### ISSUE TITLE
Upgrading to axe-core v3

### ISSUE THREAD

**Issue by drewlee** [ember-a11y/ember-a11y-testing#106]
There have been quite a number of features and bug fixes introduced into axe-core v3 ([https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md](https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md)). Are there any plans in the pipeline to update axe-core dependency to the latest release? Thanks!

**Comment by drewlee** [comment]
Hey there, seeing as there hasn't been much of a response, I don't have issue with taking up ownership in bumping up the version of axe-core. After checking what the work effort looks like, I did run into an issue in the fact that axe.run can no longer be run concurrently (https://github.com/dequelabs/axe-core/issues/1041). Obviously a problem when each component kicks off an audit. Seeing if this can be addressed on their end before implementing a workaround within this addon itself. Thanks!

**Comment by Robdel12** [comment]
Awesome! Thank you for taking this on :D

**Comment by drewlee** [comment]
I've created a pull request: https://github.com/ember-a11y/ember-a11y-testing/pull/109.

**Comment by drewlee** [comment]
Fixed by #109
