### ISSUE TITLE
Move away from jQuery

### ISSUE THREAD

**Issue by Willibaur** [ember-a11y/ember-a11y-testing#111]
Thanks for this awesome addon.

Is there any plan to move away from `jquery` soon?. I've noticed that we heavily use it according to [Docs](https://github.com/ember-a11y/ember-a11y-testing#integration-and-unit-tests)

![image](https://user-images.githubusercontent.com/12820932/47148472-b6627c80-d2c8-11e8-90bb-30f939bdc439.png)

I have used `this.element` instead in my project and test audits work fine, but I was told this approach still depends on `jQuery`. I could create a PR for updating Docs if this the right change.

Thanks

**Comment by Robdel12** [comment]
Looks like the addon doesn't use any jQuery. It'd be awesome if you submitted a PR updating the docs :)

**Comment by Willibaur** [comment]
Sure @Robdel12  #112 is in place for that change.

**Comment by Robdel12** [comment]
Closed with #112, thanks @Willibaur for the issue & contribution!
