### ISSUE TITLE
axe.run arguments are invalid on development use

### ISSUE THREAD

**Issue by Willibaur** [ember-a11y/ember-a11y-testing#113]
Hi, thanks for this awesome addon.

I'm currently using `ember-a11-testing` **0.5.4**, everything works fine within test environment, but when I try to enable the audit within `development` mode I got this error :point_down: 

![image](https://user-images.githubusercontent.com/12820932/47484842-a43a8e00-d834-11e8-97a0-79020757381c.png)

My current configuration is

```js
/* config/environment.js */

module.exports = function (environment) {
  const ENV = {
  .......
    'ember-a11y-testing': {
      componentOptions: {
        turnAuditOff: false, // Change to false to enable the audit in development
      }
    },


  };

  if (environment === 'development') {
    loggers(ENV);
  }

  .....
  return ENV;
};
```

This was working over a month ago when I added this addon, I'm not sure if #109 broke it in some aspect? :thinking: 

Thanks

**Comment by mdbiscan** [comment]
I'm also seeing this, in Ember 3.4.

**Comment by brandynbennett** [comment]
Happens for me on all versions of this addon after 0.5.2. I'm running Ember 3.4 as well.
