### ISSUE TITLE
Add renovate bot support

### ISSUE THREAD

**Issue by MelSumner** [ember-a11y/ember-a11y-testing#122]
Need to add renovate bot support to keep dependencies updated in a more automated fashion.

**Comment by Turbo87** [comment]
@MelSumner I can set up dependabot if you need help with it

**Comment by drewlee** [comment]
PR https://github.com/ember-a11y/ember-a11y-testing/pull/123 addresses this.

**Comment by drewlee** [comment]
This was completed with PR #123.
