### ISSUE TITLE
remove use of Ember.Logger

### ISSUE THREAD

**Issue by MelSumner** [ember-a11y/ember-a11y-testing#127]
We need to remove the use of Ember.Logger:

https://emberjs.github.io/rfcs/0297-deprecate-ember-logger.html
https://deprecations.emberjs.com/v3.x#toc_ember-console-deprecate-logger
Using Ember.Logger will emit warnings/deprecations since Ember 3.2.

**Comment by drewlee** [comment]
Will publish a new release of the addon after addressing #124.
