### ISSUE TITLE
Use in all tests by default

### ISSUE THREAD

**Issue by Techn1x** [ember-a11y/ember-a11y-testing#129]
I've been testing out this addon and it has been useful so far.

My only concern is that I need to add `await a11yAudit()` to every single test, which becomes a bit tedious (and also easy to miss tests by accident). I understand this was done to fix valid concerns with autorun https://github.com/ember-a11y/ember-a11y-testing/issues/63

I was hoping to be able to enable the audit for each test in a module, I tried this, with no luck
```
module('Integration | Component | progress-table', function(hooks) {
  setupRenderingTest(hooks)
  hooks.afterEach(async function() {
    await a11yAudit()
  })
})
```

Is there a way to do what I'm trying to do?

**Comment by drewlee** [comment]
@Techn1x we do this sort of thing in a couple of places. I don't think afterEach is setup to handle async, I would try:

```
module('Integration | Component | progress-table', function(hooks) {
  setupRenderingTest(hooks)
  hooks.afterEach(function() {
    await a11yAudit()
  })
})
```

**Comment by Techn1x** [comment]
Thanks! Yeah this works great
```
hooks.afterEach(function() {
  a11yAudit()
})
```
