### ISSUE TITLE
Doesn't run on browser test run

### ISSUE THREAD

**Issue by ygongdev** [ember-a11y/ember-a11y-testing#135]
I'm using `await a11yAduit()` in an `acceptance` test. I noticed that the violations are only caught when running via the `cli`, but not via the `browser`.

Is this known?

**Comment by drewlee** [comment]
@ygongdev the only situation where I've encountered this is for CSS animation effects. It's due to race conditions and timing around when axe ends up running the audit, which trips up the color contrast check. Are your failures related to color contrast? If not, is there a way to reliably reproduce what you're encountering?

**Comment by ygongdev** [comment]
Oh I see. Yeah my tests does contain a lot of animations. So that would explain why none of the browser tests are running?

**Comment by drewlee** [comment]
That's a bit unusual if none of the tests are running in the browser. The animation effects would only result in a few inconsistencies between browser and CLI results. Again, hard to say without having a way to reliably reproduce.

**Comment by drewlee** [comment]
Unable to reproduce and hasn't been validated by other reports.

**Comment by ZoeBijl** [comment]
We have a similar issue. Will be investigating further.

In short: some events are triggered on CLI but not in the local environment. The few places we saw this was with things like functions being called twice (once by the `render` helper and once by our own invocation). This was with a `mouseleave` and `mouseenter` event.

The test that most recently failed on CLI but passed locally:

```
test('flashmessage prevented from exit on mouseenter', async function (assert) {
    assert.expect(1);

    this.setProperties({
      flash: {
        preventExit() {
          assert.ok(true, 'preventExit was called');
        },
        allowExit() {},
      },
    });

    await render(hbs`<FlashMessage id="test"/>`);
    await triggerEvent('#test', 'mouseenter');
  });
```

Locally this would pass just fine. On CLI it would fail saying two asserts were run. We changed the test to fix it. But it did show that the `assert` (and thus `preventExit`) was called twice on CLI.

**Comment by NullVoxPopuli** [comment]
I'd like to re-open this issue.

In debugging the a11y testing with popovers with @ZoeBijl, we found that:
 - on MacOS `11.6.3`
   -  Chrome: `98.0.4758.80`:
     - `/tests` pass (via `ember s`)
     - headless pass (via `ember test`) (and with CI=true)
test)
  - Firefox: `97.0`
    - `/tests` pass (via `ember s`)
    - headless passes (`ember test`) (and with CI=true)

  - on Linux, Ubuntu Desktop 20.04
    - Chrome `98.0.4758.80`
      - `/tests` pass (via `ember s`)
      - headless **fails** (via `ember test`) (and with CI=true)
    - **firefox** `97.0`
      -  `/tests` passes (via `ember s`)
      - headless (tbd)
    
  - on C.I. (Linux, Ubuntu Server)
    - Chrome `95.0.4638.54`
      - headless **fails** (via `ember test`))
      
      
So we know that this is a problem with `ember-a11y-testing`:
 - and Chrome
 - on Linux
 - while in `headless` mode

**Comment by ZoeBijl** [comment]
@NullVoxPopuli and I have looked into this further. NVP found that this might be related to using an older version of ember (we’re on 3.x). Will post updates as the this develops.

**Comment by NullVoxPopuli** [comment]
I did? 😅

**Comment by ZoeBijl** [comment]
> I did? 😅

Am I misremembering events now 🙃?I thought that this might be related to the older ember version re compilation of things? Or are those unrelated/did we not yet confirm that?

**Comment by NullVoxPopuli** [comment]
Yeah, that's a different issue
