### ISSUE TITLE
Auto scroll to the bottom

### ISSUE THREAD

**Issue by ygongdev** [ember-a11y/ember-a11y-testing#136]
I was testing adding `a11yAudit` to an addon I'm working and I noticed that when I launch my app via the browser, it always scrolls to the bottom. Wondering if this is an actual issue

**Comment by drewlee** [comment]
Duplicate of https://github.com/ember-a11y/ember-a11y-testing/issues/139 and https://github.com/ember-a11y/ember-a11y-testing/issues/77.
