### ISSUE TITLE
Development mode leads to unexpected scrolling on element focus

### ISSUE THREAD

**Issue by mydea** [ember-a11y/ember-a11y-testing#139]
I'm not 100% sure what is going on, but after installing this addon, if I don't disable the development mode, my application started to auto-scroll to elements that are focused.

This repo shows the issue:
https://github.com/mydea/ember-issue-reproductions/tree/ember-a11y-testing

If you run it, scroll down a bit, and open the dropdown, everything works as expected.

Now if you enable the audit in config/environment.js, stop `ember s` and re-run it, scroll down and open the dropdown - it will scroll up.

**Comment by drewlee** [comment]
This is something that Axe does to accurately run its `color-contrast` check. For background context, you can read https://github.com/dequelabs/axe-core/issues/147, https://github.com/dequelabs/axe-core/pull/148, and https://github.com/ember-a11y/ember-a11y-testing/issues/77.

To prevent auto scrolling, you can set the `color-contrast` check to `noScroll` option.
```
ENV['ember-a11y-testing'] = {
    componentOptions: {
      axeOptions: {
        checks: {
          'color-contrast': { options: { noScroll: true } }
        }
      }
    }
  };
```
But be aware, doing so will make the Color Contrast check not as accurate, likely resulting in false negatives.

Alternatively, you can set the `restoreScroll` option to true, though this results in some jarring jumpiness.
```
ENV['ember-a11y-testing'] = {
    componentOptions: {
      axeOptions: {
        restoreScroll: true
      }
    }
  };
```

**Comment by drewlee** [comment]
Closing since this is behavior coming from axe core and not anything that the ember-a11y-testing addon can directly control.

**Comment by mydea** [comment]
Ah, thanks. As pointed out in #77 , I think it would make sense to either set this as a default or at least call it out in the readme/docs - it was very unexpected to me, and not what I would expect of a "just install it and it works" solution.
