### ISSUE TITLE
Console error in browser: "Uncaught Axe is already running'

### ISSUE THREAD

**Issue by NikkiAlgarCentrica** [ember-a11y/ember-a11y-testing#143]
I'm using ember-a11y-testing in my development environment and acceptance tests.

Within the browser, I am consistently getting this error:
**`Uncaught Axe is already running. Use 'await axe.run()' to wait for the previous run to finish before starting a new run.`**

Within the acceptance tests, they all appear to be passing, but they should not be passing as I intentionally put two h1 tags on a page.

I'm running the following versions:
ember-a11y: 0.2.2
ember-a11y-testing: 1.1.1
ember-cli: 3.1.0

I have this config in my environment.js file:
```
'ember-a11y-testing': {
      componentOptions: {
        turnAuditOff: false,
        axeOptions: {
          checks: {
            'color-contrast': {options: {noScroll: true}} // disable scrolling of color-contrast check
          }
        }
      }
    },
```

**Comment by Turbo87** [comment]
@NikkiAlgarCentrica did you find a solution for this? I seem to be hitting the same issue 🤔

**Comment by madelio** [comment]
I'm running into this as well, what was the solution?
