### ISSUE TITLE
Test to check for `main` landmark on page

### ISSUE THREAD

**Issue by SYU15** [ember-a11y/ember-a11y-testing#169]
In my application, I've discovered that a test runs to ensure that only one `main` landmark exists, however, the tests do not error if the page is missing a `main` landmark. Unsure if it is a bug since [the rule is documented here](https://dequeuniversity.com/rules/axe/3.2/landmark-one-main) or if it is missing? Either way I think it might be a good idea to fix (if this is happening to not just me)/add it to help apps become more in line with the guidelines of [1.3.1: Info and Relationships.](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html)

**Comment by MelSumner** [comment]
Can you  give us some more information so we can try to reproduce?

* How are you running the tests for your app?
* If you run `ember s` and view the app in the browser, is it missing the `<main>` element?
* if you're using Chrome, have you tried installing the aXe browser extension and running it on your page to see if it catches the error? (this can help us narrow down if it's the addon or axe-core)

Thank you!

**Comment by SYU15** [comment]
Great point @MelSumner, let me run through that list of questions and respond to them.

**Comment by scalvert** [comment]
@SYU15 were you ever able to reproduce this?

**Comment by SYU15** [comment]
@scalvert @MelSumner I just tried reproducing this and I was not able to, so perhaps this was user error on my part. Sorry about that.

**Comment by scalvert** [comment]
Thanks for checking, @SYU15. No worries - just wanted to make sure nothing was broken.
