### ISSUE TITLE
Evaluate the use cases for `ember-get-config`

### ISSUE THREAD

**Issue by scalvert** [ember-a11y/ember-a11y-testing#197]
We should evaluate under what circumstances we need to use `ember-get-config`. Ideally, users can just adapt the code to do what they want using primitives this addon exposes.

**Comment by rwjblue** [comment]
I'd prefer to change this to an explicit `setAxeOptions` API instead. Folks can invoke that from their `tests/test-helper.js` and provide the default configuration that they want, or invoke it from a specific test to set custom override values. This would replace the `_setConfigName` method here:

https://github.com/ember-a11y/ember-a11y-testing/blob/cd1a8a66f4cbbe41f2a25566bbbc7bb0a01be77b/addon-test-support/audit.ts#L26-L28

And it's usage here:

https://github.com/ember-a11y/ember-a11y-testing/blob/cd1a8a66f4cbbe41f2a25566bbbc7bb0a01be77b/addon-test-support/audit.ts#L112-L114

**Comment by drewlee** [comment]
Do we want to remove the configurations that are set in `config/environment.js` entirely or just the dependence on `ember-get-config`? Unfortunately, most of those options are leveraged by the "visual audit" feature of the component. I agree that it makes sense to set up axe options on the test side of things, but then consumers would need to define these in two different places. I think the long term means of handling this would be to extract the visual audit feature to a separate addon. But, in the short term, we should do this in a way that's backward compatible.

**Comment by scalvert** [comment]
We removed this functionality in #205.
