### ISSUE TITLE
Update demo app

### ISSUE THREAD

**Issue by MelSumner** [ember-a11y/ember-a11y-testing#252]
The demo app in the `dummy` folder is outdated and needs updating. 

(this is a placeholder issue for me, or others, to update with the specific issues in the demo app).

**Comment by KamiKillertO** [comment]
I'll look into it 👍

**Comment by drewlee** [comment]
This is something I started working on and off on a few weeks ago and ended up as PR #255.

**Comment by scalvert** [comment]
Updated as part of #255

**Comment by MelSumner** [comment]
Re-opening the issue as we still need the demo app to be there, it just needs updating.

**Comment by scalvert** [comment]
I'm a bit confused. Can you be more specific when you say 'needs updating'? #255 removed some things, but also updated the dummy app to modern constructs. I also assume when you say demo, you mean dummy, is that correct?

**Comment by scalvert** [comment]
Ping. Just trying to understand this one more. @MelSumner can you help me understand this?
