### ISSUE TITLE
axe.a11yCheck throws errors in nested components

### ISSUE THREAD

**Issue by BrianSipple** [ember-a11y/ember-a11y-testing#29]
**\[Note]** I think this is actually a larger issue in `axe-core` -- and [I PR'd my proposed changes for it there](https://github.com/dequelabs/axe-core/pull/193) -- but I also wanted to make a note here for the purposes of cross-referencing and to offer an idea for how we can address it in the meantime...

I'm seeing (so far) two different errors in the console when `axe.a11yCheck` is called on a form component with nested components: 

1. With a single nested component:
<img width="793" alt="screen shot 2016-06-17 at 12 59 28 am" src="https://cloud.githubusercontent.com/assets/5483853/16146986/b8ef1546-3435-11e6-9589-a4ef954c03b8.png">

2. With multiple nested components:
<img width="796" alt="screen shot 2016-06-17 at 12 58 37 am" src="https://cloud.githubusercontent.com/assets/5483853/16146978/ad4f9efe-3435-11e6-9e9c-f3df88ab7cff.png">

I resolved it by making these changes in `axe-core`, however, for our purposes and the way we're using `axe.a11yCheck`, it seems like we can just as well pass in string of the element ID as a selector with the [changes here]().

Interestingly, the violations still register everything appears to _run_ as expected -- but then the errors in the console do appear to cause the `ember-inspector` to crash.

**Comment by nathanhammond** [comment]
Okay, that's definitely an error in axe-core. I'm trying to get somebody from Deque to look at it. 😄 I'd rather fix this once and for all upstream than work around it here.

**Comment by nathanhammond** [comment]
Upstream has been resolved. Closing.
