### ISSUE TITLE
Add ember-cli-eslint

### ISSUE THREAD

**Issue by BrianSipple** [ember-a11y/ember-a11y-testing#37]
See: https://github.com/ember-a11y/issues/issues/2

**Comment by binhums** [comment]
I'm happy to take this now if you're not working on it.

**Comment by BrianSipple** [comment]
@binhums All yours!

**Comment by BrianSipple** [comment]
@binhums ping 😛

**Comment by trentmwillis** [comment]
Resolved by #66.
