### ISSUE TITLE
Use ember-blueprint-test-helpers for testing axe version

### ISSUE THREAD

**Issue by BrianSipple** [ember-a11y/ember-a11y-testing#40]
This was brought up in #38, but it would be better to use `ember-blueprint-test-helpers` to verify that the version of axe-core that we're adding to projects is in sync with our current dependency.

At the moment, however, [this still isn't possible](https://github.com/ember-cli/ember-cli-internal-test-helpers/issues/22)

**Comment by trentmwillis** [comment]
This is no longer needed as we don't have a blueprint (due to moving axe-core to npm).
