### ISSUE TITLE
how to properly disable audit when in dev mode?

### ISSUE THREAD

**Issue by adhamhf** [ember-a11y/ember-a11y-testing#44]
I was trying to determine if axe checks were causing a performance issue during development ( not during tests ) of a route template.  The instructions in the README simply did not work.  I finally ended up editing axe-components.js inside the installed ember-a11y-testing module and that did work.

I'm sure there is a better way though?

**Comment by MelSumner** [comment]
It's also possible that the way we intended it to work is not the way it works at the moment, so we might need to fix that. @nathanhammond or @binhums  can you weigh in here?

Editing the axe-components.js file with the turnAuditOff: true settings works for me - if this is how it is intended to work then we can make the README with more explicit instructions.

**Comment by trentmwillis** [comment]
I don't believe this is an acceptable solution as we shouldn't ever need developers to go into their `node_modules` folder.

That said, I think #51 is the correct approach to this, so I am going to close this issue in favor of that approach. Feel free to re-open if you don't think the other issue will cover your concerns.
