### ISSUE TITLE
Allow customization on a per-component basis

### ISSUE THREAD

**Issue by MelSumner** [ember-a11y/ember-a11y-testing#45]
Currently, there is no way to customize the add-on to turn off the tests on a per-component basis. 

This may be helpful in dealing with legacy systems while they are being upgraded, especially where the add-on interferes with functionality.

**Comment by trentmwillis** [comment]
Are you referring to the behavior in tests (e.g., the auto-run feature) or in development mode? The development mode stuff should be easy to turn off per-component, as you can specify the `turnAuditOff` property ([ref](https://github.com/ember-a11y/ember-a11y-testing/blob/f13a87f8fc523469330e560b8ea2e12d2bce1b1b/app/instance-initializers/axe-component.js#L63-L69)).

**Comment by MelSumner** [comment]
Thanks for reminding me to update the documentation with the correct guide for this! 👍
