### ISSUE TITLE
Test error after upgrading `@ember/test-helpers` to 2.9.0

### ISSUE THREAD

**Issue by eleenyeh** [ember-a11y/ember-a11y-testing#489]
Hello!

I'm starting to see this error consistently in integration tests after upgrading `@ember/test-helpers` to 2.9.0:
```
Assertion Failed: currentRouteName shoudl be a string
```
Looks like the new version adds an [assert](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/setup-application-context.ts#L200) on the `currentRouteName` helper which is used by [middleware-reporter](https://github.com/ember-a11y/ember-a11y-testing/blob/3947e4ee18a2c6f73eb49af08397d2d252b1e64d/addon-test-support/setup-middleware-reporter.ts#L76). I think we should avoid calling `currentRouteName` outside of acceptance tests. Let me know what you think! Thanks :)

**Comment by drewlee** [comment]
PR #491 addresses the issue.

**Comment by drewlee** [comment]
Fix has been merged and will be followed up with a release.
