### ISSUE TITLE
Upgrade axe-core in addon

### ISSUE THREAD

**Issue by MelSumner** [ember-a11y/ember-a11y-testing#49]
- upgrade axe-core version in addon
- analyze potential for something automated (feels like this should be possible, but idk yet).

**Comment by trentmwillis** [comment]
The first part of this seems done now.

> analyze potential for something automated

There's [greenkeeper](https://greenkeeper.io/), but I don't believe it works for Bower dependencies. That said, we should get off of using Bower and move instead to including it as an npm module.

**Comment by MelSumner** [comment]
@trentmwillis since that's a separate issue, I'm going to close this issue. :)
