### ISSUE TITLE
Ability to turn off in specific environment

### ISSUE THREAD

**Issue by justwright** [ember-a11y/ember-a11y-testing#51]
From the readme: 

"With the exception of `turnAuditOff`, each of the fine-grained component hooks above can instead be defined for ALL components inside of your application's config/environment.js file"

...would it be possible to add the ability to access `turnAuditOff` as well so that the auditing does not appear in, say, a staging environment?

**Comment by trentmwillis** [comment]
I see no reason why we couldn't do that. Looking at [the original PR comment](https://github.com/ember-a11y/ember-a11y-testing/pull/22), it seems like it was originally intended to be configurable. (However, I was not around at that time.)

@BrianSipple do you have remember why `turnAuditOff` is not globally configurable? Seems like it is much more likely to be used than the other options IMO.

**Comment by jonathanong** [comment]
👍  would like this configurable because this module kills the development environment

**Comment by BrianSipple** [comment]
@trentmwillis I floated the idea of making this configurable at the component level, when I initially PR'd the feature. There was a larger group [consensus against it](https://github.com/ember-a11y/ember-a11y-testing/pull/22), though, with the idea that it might discourage overall usage of the addon.  Now that we're getting more requests to enable this, though, I'd say let's do it!

**Comment by trentmwillis** [comment]
This feature has been added and released in `0.2.2`. You can now set `turnAuditOff` from within your application's config.
