### ISSUE TITLE
"ReferenceError: axe is not defined" when upgrading to 0.2.0

### ISSUE THREAD

**Issue by abought** [ember-a11y/ember-a11y-testing#61]
# Summary
When upgrading an app from ember-a11y-testing 0.1.6 to 0.2.0, I get a JS console error `ReferenceError: axe is not defined` when running `ember server`.

When I run unit tests (`ember test --server`), I do not get these errors and unit tests behave as expected. App uses Ember 2.8 (the newest LTS).

# Steps to reproduce / test case
See pull request demonstrating changes:
https://github.com/abought/demo-ember-osf/pull/6

# Attempted fixes
Also attempted to make package.json and bower.json changes to bring project in line with changes made here.
https://github.com/ember-a11y/ember-a11y-testing/pull/58

Got the same result both before and after `08238ff`.

Reran blueprint and tried with a fresh install of node_modules and bower_components.  

Tried in Chrome 56 and FF 51, Mac OS.

**Comment by abought** [comment]
Let me know if you'd like me to try additional things to help track down the cause; I'm happy to do more spadework as suggested. Thanks for the work on the new release!

**Comment by rwjblue** [comment]
I _believe_ this is the same issue as https://github.com/ember-a11y/ember-a11y-testing/issues/61, can you double check and confirm?

**Comment by abought** [comment]
> I believe this is the same issue as #61, can you double check and confirm?

This is issue 61, so, um...

Do you mean #60 ? A bit surprised if that's the case; [this chart](http://kangax.github.io/compat-table/es6/) claims the newest FF and Chrome versions support Promises natively. Then again, this could be one of those days where I learn something new.

**Comment by rwjblue** [comment]
> This is issue 61, so, um...

LOL, whoops! Yes, I was talking about #60 (sorry about that).

**Comment by abought** [comment]
> LOL, whoops! Yes, I was talking about #60 (sorry about that).

Tried instructions in #60 and restarted app. It built successfully, but got the same console error. Alas.

**Comment by trentmwillis** [comment]
Ah, forgot that `axe-core` needs to be included in development mode as well as in testing. I'll have a fix shortly.
