### ISSUE TITLE
Specify accessibility standard

### ISSUE THREAD

**Issue by thomblake** [ember-a11y/ember-a11y-testing#73]
This doesn't specify whether an app that passes these tests conforms to any particular standard for accessibility, like WCAG 2.0 or US 508. It would be nice if this was specified in the documentation, and even better if the standard used was configurable.

**Comment by trentmwillis** [comment]
As noted in the readme, this addon uses [`axe-core`](https://github.com/dequelabs/axe-core) which allows you to select from a variety of individual rules and standards to test against. You can see the defaults and additional rules/standards in their documentation: https://github.com/dequelabs/axe-core/blob/master/doc/rule-descriptions.md

**Comment by thomblake** [comment]
Awesome, thanks!
