### ISSUE TITLE
Aria 1.1 seems not supported

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [ember-a11y/ember-a11y-testing#75]
using the aria-current attribute gives an error
it has been added to https://www.w3.org/TR/wai-aria-1.1/ specifications
and was not in Aria 1.0

**Reproduction**

- have a tag with aria-selected attribute :  
`<li aria-selected="false" aria-current="false" data-option-index="0" role="option">...</li>`
- run with the ember-a11y plugin on didRender 

**Actual**

Error "aria-valid-attr" is thrown

**Expected**

No error

Is it possible to configure or modify ember-a11y so it does not trigger and error for some of the rules ?

**Comment by trentmwillis** [comment]
As noted in [the readme](https://github.com/ember-a11y/ember-a11y-testing#ember-a11y-testing), this addon is primarily a wrapper around [axe-core](https://github.com/dequelabs/axe-core) so any configuration that is possible there is also possible here.

In your case, it looks like there is an open issue for this on that end: https://github.com/dequelabs/axe-core/issues/270.
