### ISSUE TITLE
a11yAudit helper doesn't respect default axe options

### ISSUE THREAD

**Issue by ondrejsevcik** [ember-a11y/ember-a11y-testing#93]
Hi, I have disabled a few rules in my `config/environment.js` file, but they are still checked in my tests when using `a11yAudit()` helper.

I could load those default options in my test and pass them into the helper, but that doesn't sound right. I would expect that this helper respects my default config. 

Or is there any specific reason why it doesn't?

Thanks,
Ondrej

EDIT:
I've prepared simple demonstration in this repo https://github.com/ondrejsevcik/ember-a11-testing-axe-options-bug

**Comment by Robdel12** [comment]
Absolutely would :)

**Comment by ondrejsevcik** [comment]
@Robdel12 I've submitted PR. When you have a moment, could you please review it? Many thanks 🙏🏽

**Comment by Robdel12** [comment]
Closed with #100, thanks @ondrejsevcik!
